version: "3"

networks:
    backend:
services:
    mongodb:
        image: mongo
        command: mongod --dbpath /data/db --port 27017
        networks:
            - backend
        restart: unless-stopped
        ports:
            - 27017:27017
        env_file:
            - .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /todo_db:/data/db
    app_prod:
        image: blog-example:prod
        networks:
            - backend
        links:
            - mongodb
        environment:
            TERM: xterm
        tty: true
        ports:
            - 5002:5000
